#!/bin/sh

set -eu

python -m CoverageTestRunner --ignore-missing-from=without-tests
python3 -m CoverageTestRunner --ignore-missing-from=without-tests
rm -f .coverage
pep8 cliapp
# PYTHONPATH=. pylint --rcfile=pylint.conf cliapp *.py test-plugins/*.py
